-- 1. Create Products Table
CREATE TABLE IF NOT EXISTS products (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL,
  brand TEXT NOT NULL,
  price NUMERIC NOT NULL,
  image TEXT,
  description TEXT,
  composition TEXT,
  in_stock BOOLEAN DEFAULT TRUE,
  category TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. Create Hero Banners Table
CREATE TABLE IF NOT EXISTS hero_banners (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  image TEXT NOT NULL,
  link TEXT,
  title TEXT,
  subtitle TEXT,
  order_index INT DEFAULT 0,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 3. Create Orders Table
CREATE TABLE IF NOT EXISTS orders (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  customer_name TEXT NOT NULL,
  customer_email TEXT NOT NULL,
  total_amount NUMERIC NOT NULL,
  status TEXT DEFAULT 'pending' CHECK (status IN ('pending', 'dispatched', 'completed')),
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 4. Create Order Items Table
CREATE TABLE IF NOT EXISTS order_items (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_id BIGINT REFERENCES orders(id) ON DELETE CASCADE,
  product_id BIGINT REFERENCES products(id),
  quantity INT NOT NULL,
  price_at_sale NUMERIC NOT NULL
);

-- 5. Create Site Content Table (Key-Value Store)
CREATE TABLE IF NOT EXISTS site_content (
  key TEXT PRIMARY KEY,
  value TEXT NOT NULL,
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 6. Create Contact Messages Table
CREATE TABLE IF NOT EXISTS contact_messages (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  first_name TEXT NOT NULL,
  last_name TEXT NOT NULL,
  email TEXT NOT NULL,
  subject TEXT,
  message TEXT NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 7. Enable Row Level Security (RLS) - Basic Setup
-- NOTE: For a production app, you should define specific roles. 
-- For now, we allow public read and authenticated write.

ALTER TABLE products ENABLE ROW LEVEL SECURITY;
ALTER TABLE hero_banners ENABLE ROW LEVEL SECURITY;
ALTER TABLE site_content ENABLE ROW LEVEL SECURITY;
ALTER TABLE orders ENABLE ROW LEVEL SECURITY;
ALTER TABLE order_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE contact_messages ENABLE ROW LEVEL SECURITY;

-- Allow public read access
CREATE POLICY "Public read products" ON products FOR SELECT USING (true);
CREATE POLICY "Public read hero_banners" ON hero_banners FOR SELECT USING (true);
CREATE POLICY "Public read site_content" ON site_content FOR SELECT USING (true);

-- Allow public insert for orders and messages
CREATE POLICY "Public insert orders" ON orders FOR INSERT WITH CHECK (true);
CREATE POLICY "Public insert order_items" ON order_items FOR INSERT WITH CHECK (true);
CREATE POLICY "Public insert messages" ON contact_messages FOR INSERT WITH CHECK (true);

-- Allow all for authenticated users (Admin)
CREATE POLICY "Admin all products" ON products ALL USING (true);
CREATE POLICY "Admin all hero_banners" ON hero_banners ALL USING (true);
CREATE POLICY "Admin all orders" ON orders ALL USING (true);
-- 8. Sample Data
INSERT INTO products (title, brand, price, image, description, composition, in_stock, category) VALUES
('Zinc Citrate 50mg', 'Natural Factors', 1250, 'https://picsum.photos/seed/zinc/400/400', 'Zinc Citrate is a more absorbable form of zinc that helps support immune function and maintain healthy skin.', 'Zinc (Citrate) 50mg', true, 'Minerals'),
('Vitamin C 1000mg', 'Natural Factors', 1800, 'https://picsum.photos/seed/vitaminc/400/400', 'Time-release Vitamin C with Bioflavonoids for superior absorption and immune support.', 'Vitamin C 1000mg, Rosehips', true, 'Vitamins');

INSERT INTO hero_banners (image, link, order_index) VALUES
('https://picsum.photos/seed/wellness/1920/600', '/shop', 0);
